### ISSUE TITLE
Erro com caminho do Ícone

### ISSUE THREAD

**Issue by TXG0Fk3** [joeldevportugal/Calculadora-Com-Tkinter#1]
O programa não executa por conta do caminho até o ícone.
![image](https://github.com/joeldevportugal/Calculadora-Com-Tkinter/assets/137466333/f9efd0d4-b4d1-453a-b22c-c23cd152d733)

**Comment by joeldevportugal** [comment]
torcem O caminho do icon

LeovertonX ***@***.***> escreveu (domingo, 17/03/2024 à(s)
19:17):

**Comment by joeldevportugal** [comment]
@TXG0Fk3  comenta a Linha da Janela .iconbitpam ou troca o caminho do icon

**Comment by joeldevportugal** [comment]
@TXG0Fk3  ignora a mensagem anterior eu devo me ter esquecido do email aberto em algum lugar
